module.exports = {
    apps: [
        {
            name: 'pms-backend',
            script: 'bash',
            args: '-c "set -a; source .env; set +a; exec node --max-old-space-size=384 server/index.js"',
            interpreter: 'none',
            cwd: '/root/pms',
            env: {
                NODE_ENV: 'production',
                PORT: 3900,
            },
            max_memory_restart: '400M',
            restart_delay: 3000,
            max_restarts: 50,
            min_uptime: '10s',
            autorestart: true,
            watch: false,
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
            merge_logs: true,
        },
        {
            name: 'pms-engine',
            script: 'bash',
            args: '-c "set -a; source .env; set +a; exec trading_engine_python/.venv/bin/python -m trading_engine_python.main"',
            interpreter: 'none',
            cwd: '/root/pms',
            restart_delay: 5000,
            max_restarts: 50,
            min_uptime: '10s',
            autorestart: true,
            watch: false,
            log_date_format: 'YYYY-MM-DD HH:mm:ss',
            merge_logs: true,
        },
    ],
};
